"use client";

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { ChevronLeft, PackageIcon, Users, Trees, Mountain, Apple, Coins, Home, Hammer, Play, ListChecks, ShieldAlert, Globe, Trash2, Warehouse, Library } from 'lucide-react';

export default function HowToPlayPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted/50 dark:from-background dark:to-muted/30 p-4 md:p-8">
      <header className="mb-8 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Globe className="h-10 w-10 text-primary" />
          <h1 className="text-4xl font-bold tracking-tight text-foreground">
            How to Play Realm Architect
          </h1>
        </div>
        <Button asChild variant="outline">
          <Link href="/">
            <ChevronLeft className="mr-2 h-5 w-5" />
            Back to Game
          </Link>
        </Button>
      </header>

      <ScrollArea className="h-[calc(100vh-150px)]">
        <div className="space-y-6 max-w-4xl mx-auto">
          <Card className="shadow-lg">
            <CardHeader>
              <CardTitle className="text-2xl">Welcome, Architect!</CardTitle>
              <CardDescription>
                Your goal is to build a thriving realm, manage your resources wisely, complete objectives, and guide your people to prosperity. Be warned, challenges such as resource shortages and random events can lead to your realm&apos;s downfall!
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <PackageIcon className="h-6 w-6 text-accent" />
                1. Resources - The Lifeblood of Your Realm
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>You manage five key resources:</p>
              <ul className="list-disc list-inside space-y-2 pl-4">
                <li><strong className="text-foreground"><Trees className="inline h-5 w-5 mr-1 text-green-600" />Wood:</strong> Used for constructing most buildings and some upkeep. Gathered by Logging Camps and Lumber Mills.</li>
                <li><strong className="text-foreground"><Mountain className="inline h-5 w-5 mr-1 text-gray-500" />Stone:</strong> Essential for more advanced buildings and some upkeep. Gathered by Stone Quarries.</li>
                <li><strong className="text-foreground"><Apple className="inline h-5 w-5 mr-1 text-red-500" />Food:</strong> Crucial for feeding your population. Produced by Farms. Each citizen consumes a portion of food per turn (effectively 0.5 food each).</li>
                <li><strong className="text-foreground"><Coins className="inline h-5 w-5 mr-1 text-yellow-500" />Gold:</strong> Needed for building upkeep, trade, and some constructions. Generated by Gold Mines and Markets. If your gold runs out, many buildings will cease production!</li>
                <li><strong className="text-foreground"><Users className="inline h-5 w-5 mr-1 text-blue-500" />Population:</strong> Represents your citizens. Displayed as Current / Max Capacity. More population allows for more workers but also increases food consumption. Population increases if there is available housing capacity (from <Home className="inline h-4 w-4" /> Huts) and sufficient food. If your population reaches zero, it&apos;s Game Over! If population exceeds housing capacity, citizens will leave.</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <Hammer className="h-6 w-6 text-accent" />
                2. Construction - Shaping Your Realm
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>Use the &quot;Construct Buildings&quot; menu in the sidebar to select and place buildings.</p>
              <ul className="list-disc list-inside space-y-2 pl-4">
                <li>Each building has a <strong className="text-foreground">cost</strong> in resources (Wood, Stone, Gold).</li>
                <li>Most buildings have an <strong className="text-foreground">upkeep</strong> cost per turn (e.g., food or gold).</li>
                <li>Buildings <strong className="text-foreground">produce</strong> resources or provide other benefits (e.g., <Home className="inline h-4 w-4" /> Huts provide housing capacity, <Library className="inline h-4 w-4" /> Libraries provide passive bonuses).</li>
                <li>You can <strong className="text-foreground">demolish</strong> existing buildings by clicking the <Trash2 className="inline h-4 w-4 text-destructive" /> icon next to them in the &quot;Realm Status&quot; card. You&apos;ll recover a portion of their construction cost. Demolishing housing can lead to citizens leaving if capacity becomes too low.</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <Play className="h-6 w-6 text-accent" />
                3. Turns - The Flow of Time
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>Click the &quot;Advance to Next Turn&quot; button to progress the game.</p>
              <p>During each turn:</p>
              <ul className="list-disc list-inside space-y-2 pl-4">
                <li><strong className="text-foreground">Immigration:</strong> New citizens may arrive if housing and food are sufficient.</li>
                <li>Upkeep for buildings is deducted from your resources.</li>
                <li>Buildings produce resources (if upkeep is met and gold is not zero for most buildings).</li>
                <li>Your population consumes food.</li>
                <li><strong className="text-foreground">Starvation:</strong> If food runs out, your citizens will start to perish!</li>
                <li><strong className="text-foreground">Overcrowding:</strong> If population exceeds housing capacity, citizens will leave.</li>
                <li><strong className="text-foreground">Work Stoppage:</strong> If gold runs out, most buildings will stop producing resources.</li>
                <li><strong className="text-foreground">Random Events:</strong> Unexpected events can occur, bringing boons or challenges. Read the event messages carefully!</li>
                <li><strong className="text-foreground">Quests & Achievements:</strong> Your progress towards objectives is checked.</li>
                 <li><strong className="text-foreground">Periodic Gifts:</strong> Every 10 turns, you&apos;ll receive a small gift of a random resource.</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <ListChecks className="h-6 w-6 text-accent" />
                4. Objectives - Quests & Achievements
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>The &quot;Objectives&quot; panel in the sidebar lists active Quests and Achievements.</p>
              <ul className="list-disc list-inside space-y-2 pl-4">
                <li><strong className="text-foreground">Quests:</strong> Specific tasks to complete for immediate rewards.</li>
                <li><strong className="text-foreground">Achievements:</strong> Milestones that mark significant progress in your realm.</li>
              </ul>
              <p>Completing objectives helps you grow and unlock new possibilities.</p>
            </CardContent>
          </Card>

          <Card className="shadow-lg border-destructive">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl text-destructive">
                <ShieldAlert className="h-6 w-6" />
                5. Game Over - The End of an Era
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>Your realm will fall if your <strong className="text-destructive">population drops to zero</strong>. This can happen due to starvation, events, or citizens leaving due to lack of housing.</p>
              <p>Manage your resources carefully to avoid this fate!</p>
            </CardContent>
          </Card>

          <Card className="shadow-lg">
            <CardHeader>
              <CardTitle className="text-xl">Tips for Success</CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              <ul className="list-disc list-inside space-y-2 pl-4">
                <li><strong className="text-foreground">Build Huts:</strong> Ensure you have enough housing capacity for your desired population.</li>
                <li><strong className="text-foreground">Balance your economy:</strong> Don&apos;t expand too quickly without securing food and gold production.</li>
                <li><strong className="text-foreground">Pay attention to upkeep:</strong> Buildings cost resources every turn.</li>
                <li><strong className="text-foreground">Read event messages:</strong> They provide crucial information.</li>
                <li><strong className="text-foreground">Complete quests:</strong> They offer valuable rewards.</li>
                <li><strong className="text-foreground">Build <Warehouse className="inline h-4 w-4" /> Warehouses:</strong> They can help mitigate losses from negative events like pests or fires.</li>
                <li><strong className="text-foreground">Build <Library className="inline h-4 w-4" /> Libraries:</strong> They provide a passive boost to Wood, Stone, and Food production.</li>
              </ul>
            </CardContent>
          </Card>

           <div className="text-center py-6">
             <Button asChild size="lg">
              <Link href="/">
                <ChevronLeft className="mr-2 h-5 w-5" />
                Return to Your Realm
              </Link>
            </Button>
           </div>

        </div>
      </ScrollArea>
    </div>
  );
}

